language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "earagon1"
branches:
  only:
    - master
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm install
  - npm test --coverage && sonar-scanner
