language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "earagon1"
branches:
  only:
    - master
script:
  - npm install
  - npm run test && npm run tslint && npm test --coverage && sonar-scanner
