language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "earagon1"
branches:
  only:
    - master
before_script:
  - npm install -g --silent @angular/cli@7.3.5
script:
  - npm run test && npm run tslint && sonar-scanner
