language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "earagon1"
branches:
  only:
    - master
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
    - npm install
    - sonar-scanner
