language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "earagon1"
     token:
       secure: "4166bbd1e86538d4a7d462b95e43fddc1d3c9aa3" # encrypted value of your token
branches:
  only:
    - master
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
    - npm install
    - npm install karma karma-coverage --save-dev
    - sonar-scanner
