language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "earagon1"
    token:
      secure: "258964df3f4989029eb182d35401e0cc64e97fc0" # encrypted value of your token
     
branches:
  only:
    - master
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
    - npm install
    - npm install karma karma-coverage --save-dev
    - sonar-scanner
