version: 2
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  workflows:
  main:
    jobs:
      - commit:
          context: sonarcloud
      - sonarcloud/check_quality_gate:
          context: sonarcloud
          requires:
            - push
jobs:
  build:
    working_directory: ~/Escuela2
    docker:
      - image: circleci/node:10-browsers
    context: SonarCloud
    steps:
      - checkout
      - restore_cache:
          key: Escuela2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: Escuela2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm install karma karma-coverage --save-dev
      - sonarcloud/scan

