version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
jobs:
  build:
    docker:
      - image: 'cimg/node:16.10.0'
    steps:
    - checkout
    - npm install
    - npm install karma karma-coverage --save-dev
    - sonarcloud/scan
workflows:
  my-workflow:
    jobs:
      - build:
          context: sonarcloud
